### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Romeo67511** [jabrail-chumakov/Multi-floor-navigation-with-ROS2#1]
I tried this project, but after I run the first command line, no map is loaded. At the same time, there is no test.py file in the warehouse. Can you add something? Thank you

**Comment by jabrail-chumakov** [comment]
Hi @Romeo67511,
I uploaded an entire workspace including some necessary files missing. You should be able to access and run the workspace now, though you'll likely encounter some errors initially. The errors will probably be related to incorrect directory paths since I set up the workspace on my own laptop. I'm sure you can figure out which files have incorrect directory references and need to be pointed to the right locations and files in your own system. Once you fix those issues by updating the paths, the workspace should function properly. Good luck!
